WIFI_SSID = "YOUR_WIFI_SSID"
WIFI_PASSWORD = "YOUR_WIFI_PASSWORD"

MQTT_HOST = "YOUR_AZURE_MQTT_HOST"
MQTT_PORT = 1883
MQTT_CLIENT_ID = "esp32_aquaponics_01"

# DS18B20 temperature sensors (OneWire)
PIN_TEMP_WATER = 4
PIN_TEMP_BED = 5

# DHT22 air sensors
PIN_DHT_INSIDE = 14
PIN_DHT_OUTSIDE = 27

# HC-SR04 ultrasonic water level
PIN_TRIG = 12
PIN_ECHO = 13

# Atlas Scientific UART (EZO-pH, EZO-DO via UART)
PIN_UART_TX = 17
PIN_UART_RX = 16

PUBLISH_INTERVAL_SEC = 30
